// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
package user_transaction_history

const (
	ColUserTransactionHistory                   = "user_transaction_history"
	FUserTransactionHistoryTransactionID        = "transaction_id"
	FUserTransactionHistoryTransactionType      = "transaction_type"
	FUserTransactionHistoryProfileID            = "profile_id"
	FUserTransactionHistoryStatus               = "status"
	FUserTransactionHistoryPointAmount          = "point_amount"
	FUserTransactionHistoryPointType            = "point_type"
	FUserTransactionHistoryTotalAmount          = "total_amount"
	FUserTransactionHistoryCurrency             = "currency"
	FUserTransactionHistoryPaymentTransactionID = "payment_transaction_id"
	FUserTransactionHistorySource               = "source"
	FUserTransactionHistorySourceTime           = "source_time"
	FUserTransactionHistorySourceType           = "source_type"
	FUserTransactionHistoryCreatedAt            = "created_at"
	FUserTransactionHistoryUpdatedAt            = "updated_at"
)
